--[[
    Fisch Loader
  - Get Warn/Ban = executor issue / q.r2s brain issue
]]


local Manager = loadstring(game:HttpGet("https://raw.githubusercontent.com/4lpaca-pin/Arceney/refs/heads/main/interface/LoaderManager.luau"))();

Manager("https://api.luarmor.net/files/v3/loaders/33aed7d464e90ab9943d58f21cd24d00.lua","https://api.luarmor.net/files/v3/loaders/33aed7d464e90ab9943d58f21cd24d00.lua",true);
