return {
    ["DRAGON_QUEST_ENABLED"] = true,
    ["ATOMIC_ENEMIES"] = false,
    ["GIFTING_ENABLED"] = true,
    ["ENVIRONMENT_MUSIC_ENABLED"] = false,
    ["CREWS_ENABLED"] = true,
    ["OFFLINE_GIFTING_ENABLED"] = true,
    ["COMPASS_REWORK_ENABLED"] = false,
    ["FRUIT_ACCESSORIES_ENABLED"] = true,
    ["SUBCLASSES"] = {
        ["Helmsman"] = false,
        ["Shipwright"] = true
    },
    ["ENVIRONMENTS_ENABLED"] = true,
    ["XMAS_RAID_ENABLED"] = false,
    ["FISHING_FLAGS"] = {
        ["ENABLE_SPECIAL_FISHING_SPOTS"] = true,
        ["ENABLE_SUBMERGED_ISLAND_FISHING_SPOTS"] = true
    },
    ["HIDDEN_ABILITY_QUESTS_ON_HUD"] = false,
    ["RED_CORRUPTION_EVENT_ENABLED"] = false,
    ["FRUIT_SKINS_ENABLED"] = true,
    ["HIDDEN_SKILLS_ENABLED"] = true,
    ["ENEMY_NETWORK_PROTECTIONS"] = true,
    ["ROBUX_SKINS_REQUIRE_PERMANENT"] = false,
    ["SUMMER_TOKEN_LIGHTNING_EVENT_ENABLED"] = false,
    ["OLD_COMBAT_SYSTEM_VISUALIZE_HITBOXES"] = false,
    ["CONSUMABLES_ENABLED"] = true,
    ["ENCHANT_USES_NEW_SERVICE"] = true,
    ["CELESTIAL_DOMAIN_EVENT_ENABLED"] = false,
    ["CHROMATIC_SKINS_ENABLED"] = true,
    ["ROBLOX_ANALYTICS_ENABLED"] = true,
    ["CELEBRATION_REALM"] = {
        ["TELEPORTATION_ENABLED"] = false,
        ["ENABLED"] = false
    },
    ["PVP_ARENA_FLAGS"] = {
        ["SUMMER_TOKENS_ENABLED"] = false
    },
    ["CUSTOM_ANALYTICS_ENABLED"] = false,
    ["WEATHER_ENABLED"] = true,
    ["SUBCLASSES_ENABLED"] = true,
    ["ENABLE_SUBMERGED_ISLAND_LOW_TIDE"] = true,
    ["ALLOW_VIRTUAL_REMOTES"] = true,
    ["COMBAT_REMOTE_THREAD"] = true,
    ["ANGEL_QUEST_ENABLED"] = false,
    ["NEW_MOBILE_CONTROLS_OPTION_ENABLED"] = false,
    ["NEW_COMBAT_SYSTEM_VISUALIZE_HITBOXES"] = false,
    ["SUMMER_TOKEN_SLAP_BATTLES"] = false
}
