return local z = {
    ["ELEMENTS"] = {
        ["Transformation"] = {
            ["Text"] = [=[Can transform]=],
            ["Images"] = {
                ["100x100"] = [=[rbxassetid://85635919480021]=],
                ["34x34"] = [=[rbxassetid://116255990226292]=],
                ["845x845"] = [=[rbxassetid://18522364352]=]
            }
        },
        ["Awakening"] = {
            ["Text"] = [=[Unlockable awakening]=],
            ["Images"] = {
                ["100x100"] = [=[rbxassetid://93842515161395]=],
                ["34x34"] = [=[rbxassetid://138098911321101]=],
                ["845x845"] = [=[rbxassetid://18556567876]=]
            }
        },
        ["M1"] = {
            ["Text"] = [=[Can M1]=],
            ["Images"] = {
                ["100x100"] = [=[rbxassetid://124422403020828]=],
                ["34x34"] = [=[rbxassetid://110722339497487]=],
                ["845x845"] = [=[rbxassetid://18522363952]=]
            }
        },
        ["Elemental"] = {
            ["Text"] = [=[Immune to weak attacks]=],
            ["Images"] = {
                ["100x100"] = [=[rbxassetid://116857012834974]=],
                ["34x34"] = [=[rbxassetid://99096073700387]=],
                ["845x845"] = [=[rbxassetid://18522364171]=]
            }
        }
    },
    ["DATA"] = {
        ["Buddha-Buddha"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                },
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Transforms the user into a giant Buddha, increasing the users size, power, and defense, making it perfect for farming.]=]
        },
        ["Sand-Sand"] = {
            ["Rarity"] = {
                ["Value"] = 1,
                ["Name"] = [=[Uncommon]=]
            },
            ["Elements"] = {
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                },
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                }
            },
            ["Description"] = [=[Grants control over sand, with abilities to trap and attack.]=]
        },
        ["Smoke-Smoke"] = {
            ["Rarity"] = {
                ["Value"] = 0,
                ["Name"] = [=[Common]=]
            },
            ["Elements"] = {
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                }
            },
            ["Description"] = [=[Offers the user an arsenal of smoke attacks, and is useful for grinding as a new player.]=]
        },
        ["Creation-Creation"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Creates barriers for defense and can trap enemies.]=]
        },
        ["Ice-Ice"] = {
            ["Rarity"] = {
                ["Value"] = 1,
                ["Name"] = [=[Uncommon]=]
            },
            ["Elements"] = {
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                },
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                }
            },
            ["Description"] = [=[Allows the user to manipulate ice, freezing their foes in place.]=]
        },
        ["Tiger-Tiger"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1 transformed]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Allows the user to turn into a tiger, granting enhanced agility and powerful melee attacks.]=]
        },
        ["Diamond-Diamond"] = {
            ["Rarity"] = {
                ["Value"] = 1,
                ["Name"] = [=[Uncommon]=]
            },
            ["Elements"] = {
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Turns the user into diamond, enhancing defense and providing sharp attacks.]=]
        },
        ["Light-Light"] = {
            ["Rarity"] = {
                ["Value"] = 2,
                ["Name"] = [=[Rare]=]
            },
            ["Elements"] = {
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                },
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Grants light-speed movement and powerful light-based attacks.]=]
        },
        ["T-Rex-T-Rex"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Transforms the user into a T-Rex, granting powerful close-range attacks.]=]
        },
        ["Dragon-Dragon"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Transforms the user into a mighty dragon, allowing them to rule over the skies with scorching flames.]=]
        },
        ["Portal-Portal"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Allows the user to instantly travel to any location, or create a portal to a dimension of their own.]=]
        },
        ["Blizzard-Blizzard"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                }
            },
            ["Description"] = [=[Grants control over powerful ice storms, which can be used to blind your enemies. ]=]
        },
        ["Gravity-Gravity"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Allows the user to manipulate gravity, controlling the battlefield.]=]
        },
        ["Spin-Spin"] = {
            ["Rarity"] = {
                ["Value"] = 0,
                ["Name"] = [=[Common]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Provides spinning attacks which will injure enemies with razor sharp wind slashes.]=]
        },
        ["Blade-Blade"] = {
            ["Rarity"] = {
                ["Value"] = 0,
                ["Name"] = [=[Common]=]
            },
            ["Elements"] = {
                ["Elemental"] = {
                    ["Text"] = [=[Immune to sword attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Grants the user a body of blades, offering immunity to sword attacks and sharp striking abilities.]=]
        },
        ["Rubber-Rubber"] = {
            ["Rarity"] = {
                ["Value"] = 2,
                ["Name"] = [=[Rare]=]
            },
            ["Elements"] = {
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Grants the user a rubber body, immune to electric attacks and stretchy enough to deal a barrage of offensive attacks.]=]
        },
        ["Spring-Spring"] = {
            ["Rarity"] = {
                ["Value"] = 0,
                ["Name"] = [=[Common]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Offers spring-like movement and bouncing attacks.]=]
        },
        ["Quake-Quake"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                }
            },
            ["Description"] = [=[Provides the ability to create shockwaves, dealing massive area damage.]=]
        },
        ["Eagle-Eagle"] = {
            ["Rarity"] = {
                ["Value"] = 1,
                ["Name"] = [=[Uncommon]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Gives the user wings, and bird-like attacks.]=]
        },
        ["Bomb-Bomb"] = {
            ["Rarity"] = {
                ["Value"] = 0,
                ["Name"] = [=[Common]=]
            },
            ["Elements"] = {
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Provides the user with a wide range of explosive attacks.]=]
        },
        ["Venom-Venom"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                }
            },
            ["Description"] = [=[Transforms the user into a venomous hydra, granting the user poison-based attacks that damage over time.]=]
        },
        ["Spider-Spider"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                }
            },
            ["Description"] = [=[Grants spider-like abilities, including web attacks and agility.]=]
        },
        ["Spirit-Spirit"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Grants the user the ability to manipulate spirits, which can offer the user heavenly buffs to themselves or disastrous traps to their enemies.]=]
        },
        ["Love-Love"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Use charming abilities to debuff enemies, and to summon your Besto Friendo.]=]
        },
        ["Ghost-Ghost"] = {
            ["Rarity"] = {
                ["Value"] = 2,
                ["Name"] = [=[Rare]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Allows the user to transcend the barrier between life and death, granting an extra life and paranormal abilities.]=]
        },
        ["Sound-Sound"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Use instrument based attacks, or ride along sheets of music to power-up this Fruit. ]=]
        },
        ["Kitsune-Kitsune"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Grants fox-like abilities, with amazing agility and blue fire-based attacks. Damage enemies to fully transform into the mythical Kitsune.]=]
        },
        ["Gas-Gas"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                },
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                },
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                }
            },
            ["Description"] = [=[Allows the user to exhale clouds of explosive gas and transform into a powerful gaseous knight.]=]
        },
        ["Magma-Magma"] = {
            ["Rarity"] = {
                ["Value"] = 2,
                ["Name"] = [=[Rare]=]
            },
            ["Elements"] = {
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                },
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                }
            },
            ["Description"] = [=[Grants magma-based attacks that deal high damage and burn enemies.]=]
        },
        ["Phoenix-Phoenix"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                },
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1 awakened]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Grants regenerative abilities, powerful fire-based attacks, and the ability to transform into full body Phoenix.]=]
        },
        ["Lightning-Lightning"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Provides electric-based attacks, which have stun based effects.]=]
        },
        ["Flame-Flame"] = {
            ["Rarity"] = {
                ["Value"] = 1,
                ["Name"] = [=[Uncommon]=]
            },
            ["Elements"] = {
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                },
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                }
            },
            ["Description"] = [=[Enables the user to control and create fire, forcing enemies to steer clear if you don't want to burn.]=]
        },
        ["Rocket-Rocket"] = {
            ["Rarity"] = {
                ["Value"] = 0,
                ["Name"] = [=[Common]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Grants explosive movement abilities, allowing quick travel and attacks.]=]
        },
        ["Control-Control"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Allows the user to control objects and enemies within a specified area.]=]
        },
        ["Mammoth-Mammoth"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1 transformed]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Transforms the user into a mammoth, providing strength and size.]=]
        },
        ["Dark-Dark"] = {
            ["Rarity"] = {
                ["Value"] = 1,
                ["Name"] = [=[Uncommon]=]
            },
            ["Elements"] = {
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                },
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                }
            },
            ["Description"] = [=[Provides darkness-based abilities which pull enemies in closer to you.]=]
        },
        ["Spike-Spike"] = {
            ["Rarity"] = {
                ["Value"] = 0,
                ["Name"] = [=[Common]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Grants the user sharp spikes on their body, full of offensive attacks skills.]=]
        },
        ["Pain-Pain"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Inflicts pain-based attacks, causing damage over time.]=]
        },
        ["Dough-Dough"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                },
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1 awakened]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Provides sticky and flexible dough-based attacks.]=]
        },
        ["Shadow-Shadow"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Grants life-leeching abilities, useful for tactical takedowns of your enemies.]=]
        },
        ["Yeti-Yeti"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1 transformed]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Allows the user to turn into a hulking snow beast with cold attacks and ground-shaking strength.]=]
        }
    },
    ["getNames"] = function()end --[[function: 0x1af018c71bfc1645]],
    ["TryGet"] = function()end --[[function: 0xad7c8c00db4443f5]],
    ["Get"] = function()end --[[function: 0xd61489d42c934195]],
    ["List"] = {
        ["Buddha-Buddha"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                },
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Transforms the user into a giant Buddha, increasing the users size, power, and defense, making it perfect for farming.]=]
        },
        ["Sand-Sand"] = {
            ["Rarity"] = {
                ["Value"] = 1,
                ["Name"] = [=[Uncommon]=]
            },
            ["Elements"] = {
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                },
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                }
            },
            ["Description"] = [=[Grants control over sand, with abilities to trap and attack.]=]
        },
        ["Smoke-Smoke"] = {
            ["Rarity"] = {
                ["Value"] = 0,
                ["Name"] = [=[Common]=]
            },
            ["Elements"] = {
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                }
            },
            ["Description"] = [=[Offers the user an arsenal of smoke attacks, and is useful for grinding as a new player.]=]
        },
        ["Creation-Creation"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Creates barriers for defense and can trap enemies.]=]
        },
        ["Ice-Ice"] = {
            ["Rarity"] = {
                ["Value"] = 1,
                ["Name"] = [=[Uncommon]=]
            },
            ["Elements"] = {
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                },
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                }
            },
            ["Description"] = [=[Allows the user to manipulate ice, freezing their foes in place.]=]
        },
        ["Tiger-Tiger"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1 transformed]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Allows the user to turn into a tiger, granting enhanced agility and powerful melee attacks.]=]
        },
        ["Diamond-Diamond"] = {
            ["Rarity"] = {
                ["Value"] = 1,
                ["Name"] = [=[Uncommon]=]
            },
            ["Elements"] = {
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Turns the user into diamond, enhancing defense and providing sharp attacks.]=]
        },
        ["Light-Light"] = {
            ["Rarity"] = {
                ["Value"] = 2,
                ["Name"] = [=[Rare]=]
            },
            ["Elements"] = {
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                },
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Grants light-speed movement and powerful light-based attacks.]=]
        },
        ["T-Rex-T-Rex"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Transforms the user into a T-Rex, granting powerful close-range attacks.]=]
        },
        ["Dragon-Dragon"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Transforms the user into a mighty dragon, allowing them to rule over the skies with scorching flames.]=]
        },
        ["Portal-Portal"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Allows the user to instantly travel to any location, or create a portal to a dimension of their own.]=]
        },
        ["Blizzard-Blizzard"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                }
            },
            ["Description"] = [=[Grants control over powerful ice storms, which can be used to blind your enemies. ]=]
        },
        ["Gravity-Gravity"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Allows the user to manipulate gravity, controlling the battlefield.]=]
        },
        ["Spin-Spin"] = {
            ["Rarity"] = {
                ["Value"] = 0,
                ["Name"] = [=[Common]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Provides spinning attacks which will injure enemies with razor sharp wind slashes.]=]
        },
        ["Blade-Blade"] = {
            ["Rarity"] = {
                ["Value"] = 0,
                ["Name"] = [=[Common]=]
            },
            ["Elements"] = {
                ["Elemental"] = {
                    ["Text"] = [=[Immune to sword attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Grants the user a body of blades, offering immunity to sword attacks and sharp striking abilities.]=]
        },
        ["Rubber-Rubber"] = {
            ["Rarity"] = {
                ["Value"] = 2,
                ["Name"] = [=[Rare]=]
            },
            ["Elements"] = {
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Grants the user a rubber body, immune to electric attacks and stretchy enough to deal a barrage of offensive attacks.]=]
        },
        ["Spring-Spring"] = {
            ["Rarity"] = {
                ["Value"] = 0,
                ["Name"] = [=[Common]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Offers spring-like movement and bouncing attacks.]=]
        },
        ["Quake-Quake"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                }
            },
            ["Description"] = [=[Provides the ability to create shockwaves, dealing massive area damage.]=]
        },
        ["Eagle-Eagle"] = {
            ["Rarity"] = {
                ["Value"] = 1,
                ["Name"] = [=[Uncommon]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Gives the user wings, and bird-like attacks.]=]
        },
        ["Bomb-Bomb"] = {
            ["Rarity"] = {
                ["Value"] = 0,
                ["Name"] = [=[Common]=]
            },
            ["Elements"] = {
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Provides the user with a wide range of explosive attacks.]=]
        },
        ["Venom-Venom"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                }
            },
            ["Description"] = [=[Transforms the user into a venomous hydra, granting the user poison-based attacks that damage over time.]=]
        },
        ["Spider-Spider"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                }
            },
            ["Description"] = [=[Grants spider-like abilities, including web attacks and agility.]=]
        },
        ["Spirit-Spirit"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Grants the user the ability to manipulate spirits, which can offer the user heavenly buffs to themselves or disastrous traps to their enemies.]=]
        },
        ["Love-Love"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Use charming abilities to debuff enemies, and to summon your Besto Friendo.]=]
        },
        ["Ghost-Ghost"] = {
            ["Rarity"] = {
                ["Value"] = 2,
                ["Name"] = [=[Rare]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Allows the user to transcend the barrier between life and death, granting an extra life and paranormal abilities.]=]
        },
        ["Sound-Sound"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Use instrument based attacks, or ride along sheets of music to power-up this Fruit. ]=]
        },
        ["Kitsune-Kitsune"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Grants fox-like abilities, with amazing agility and blue fire-based attacks. Damage enemies to fully transform into the mythical Kitsune.]=]
        },
        ["Gas-Gas"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                },
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                },
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                }
            },
            ["Description"] = [=[Allows the user to exhale clouds of explosive gas and transform into a powerful gaseous knight.]=]
        },
        ["Magma-Magma"] = {
            ["Rarity"] = {
                ["Value"] = 2,
                ["Name"] = [=[Rare]=]
            },
            ["Elements"] = {
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                },
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                }
            },
            ["Description"] = [=[Grants magma-based attacks that deal high damage and burn enemies.]=]
        },
        ["Phoenix-Phoenix"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                },
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1 awakened]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Grants regenerative abilities, powerful fire-based attacks, and the ability to transform into full body Phoenix.]=]
        },
        ["Lightning-Lightning"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Provides electric-based attacks, which have stun based effects.]=]
        },
        ["Flame-Flame"] = {
            ["Rarity"] = {
                ["Value"] = 1,
                ["Name"] = [=[Uncommon]=]
            },
            ["Elements"] = {
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                },
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                }
            },
            ["Description"] = [=[Enables the user to control and create fire, forcing enemies to steer clear if you don't want to burn.]=]
        },
        ["Rocket-Rocket"] = {
            ["Rarity"] = {
                ["Value"] = 0,
                ["Name"] = [=[Common]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Grants explosive movement abilities, allowing quick travel and attacks.]=]
        },
        ["Control-Control"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Allows the user to control objects and enemies within a specified area.]=]
        },
        ["Mammoth-Mammoth"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1 transformed]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Transforms the user into a mammoth, providing strength and size.]=]
        },
        ["Dark-Dark"] = {
            ["Rarity"] = {
                ["Value"] = 1,
                ["Name"] = [=[Uncommon]=]
            },
            ["Elements"] = {
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                },
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                }
            },
            ["Description"] = [=[Provides darkness-based abilities which pull enemies in closer to you.]=]
        },
        ["Spike-Spike"] = {
            ["Rarity"] = {
                ["Value"] = 0,
                ["Name"] = [=[Common]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Grants the user sharp spikes on their body, full of offensive attacks skills.]=]
        },
        ["Pain-Pain"] = {
            ["Rarity"] = {
                ["Value"] = 3,
                ["Name"] = [=[Legendary]=]
            },
            ["Elements"] = {
                ["M1"] = {
                    ["Text"] = [=[Can M1]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Inflicts pain-based attacks, causing damage over time.]=]
        },
        ["Dough-Dough"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["Awakening"] = {
                    ["Text"] = [=[Unlockable awakening]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://93842515161395]=],
                        ["34x34"] = [=[rbxassetid://138098911321101]=],
                        ["845x845"] = [=[rbxassetid://18556567876]=]
                    }
                },
                ["Elemental"] = {
                    ["Text"] = [=[Immune to weak attacks]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://116857012834974]=],
                        ["34x34"] = [=[rbxassetid://99096073700387]=],
                        ["845x845"] = [=[rbxassetid://18522364171]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1 awakened]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Provides sticky and flexible dough-based attacks.]=]
        },
        ["Shadow-Shadow"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {},
            ["Description"] = [=[Grants life-leeching abilities, useful for tactical takedowns of your enemies.]=]
        },
        ["Yeti-Yeti"] = {
            ["Rarity"] = {
                ["Value"] = 4,
                ["Name"] = [=[Mythical]=]
            },
            ["Elements"] = {
                ["Transformation"] = {
                    ["Text"] = [=[Can transform]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://85635919480021]=],
                        ["34x34"] = [=[rbxassetid://116255990226292]=],
                        ["845x845"] = [=[rbxassetid://18522364352]=]
                    }
                },
                ["M1"] = {
                    ["Text"] = [=[Can M1 transformed]=],
                    ["Images"] = {
                        ["100x100"] = [=[rbxassetid://124422403020828]=],
                        ["34x34"] = [=[rbxassetid://110722339497487]=],
                        ["845x845"] = [=[rbxassetid://18522363952]=]
                    }
                }
            },
            ["Description"] = [=[Allows the user to turn into a hulking snow beast with cold attacks and ground-shaking strength.]=]
        }
    },
    ["Elements"] = {
        ["Transformation"] = {
            ["Text"] = [=[Can transform]=],
            ["Images"] = {
                ["100x100"] = [=[rbxassetid://85635919480021]=],
                ["34x34"] = [=[rbxassetid://116255990226292]=],
                ["845x845"] = [=[rbxassetid://18522364352]=]
            }
        },
        ["Awakening"] = {
            ["Text"] = [=[Unlockable awakening]=],
            ["Images"] = {
                ["100x100"] = [=[rbxassetid://93842515161395]=],
                ["34x34"] = [=[rbxassetid://138098911321101]=],
                ["845x845"] = [=[rbxassetid://18556567876]=]
            }
        },
        ["M1"] = {
            ["Text"] = [=[Can M1]=],
            ["Images"] = {
                ["100x100"] = [=[rbxassetid://124422403020828]=],
                ["34x34"] = [=[rbxassetid://110722339497487]=],
                ["845x845"] = [=[rbxassetid://18522363952]=]
            }
        },
        ["Elemental"] = {
            ["Text"] = [=[Immune to weak attacks]=],
            ["Images"] = {
                ["100x100"] = [=[rbxassetid://116857012834974]=],
                ["34x34"] = [=[rbxassetid://99096073700387]=],
                ["845x845"] = [=[rbxassetid://18522364171]=]
            }
        }
    },
    ["match"] = function()end --[[function: 0xce47df95b0e9a975]],
    ["tryGet"] = function()end --[[function: 0x1f47999b3ca3c635]],
    ["get"] = function()end --[[function: 0xe789a4a20d344d55]]
}
